/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#333535',
        'surface-container-lowest': '#0c0f0f',
        'on-surface-variant': '#ebbbb4',
        'on-surface': '#e2e2e2',
        'primary-fixed': '#ffdad4',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'error-container': '#93000a',
        'surface-dim': '#121414',
        'surface': '#121414',
        'on-tertiary': '#303030',
        'primary-container': '#ff5540',
        'on-secondary': '#313030',
        'outline-variant': '#603e39',
        'on-secondary-fixed-variant': '#474646',
        'on-primary-fixed-variant': '#930100',
        'error': '#ffb4ab',
        'surface-tint': '#ffb4a8',
        'outline': '#b18780',
        'on-tertiary-fixed': '#1b1c1c',
        'inverse-on-surface': '#2f3131',
        'background': '#121414',
        'surface-bright': '#37393a',
        'tertiary-container': '#929090',
        'tertiary-fixed-dim': '#c8c6c5',
        'secondary': '#c8c6c5',
        'secondary-fixed': '#e5e2e1',
        'surface-container': '#1e2020',
        'on-tertiary-fixed-variant': '#474746',
        'on-primary-container': '#5c0000',
        'on-primary-fixed': '#410000',
        'on-primary': '#690100',
        'surface-container-highest': '#333535',
        'on-error': '#690005',
        'tertiary-fixed': '#e5e2e1',
        'on-tertiary-container': '#2a2a2a',
        'surface-container-high': '#282a2b',
        'on-secondary-container': '#bab8b7',
        'surface-container-low': '#1a1c1c',
        'primary-fixed-dim': '#ffb4a8',
        'tertiary': '#c8c6c5',
        'primary': '#ffb4a8',
        'inverse-primary': '#c00100',
        'on-error-container': '#ffdad6',
        'on-background': '#e2e2e2',
        'secondary-container': '#4a4949',
        'inverse-surface': '#e2e2e2',
        'brand-red': '#FF0000',
        'brand-green': '#39FF14',
        'brand-amber': '#FFBF00',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.4), 0 1px 2px rgba(0,0,0,0.3)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.5), 0 2px 4px rgba(0,0,0,0.3)',
        'glow-red': '0 0 20px rgba(255,85,64,0.15)',
        'glow-green': '0 0 12px rgba(57,255,20,0.3)',
      },
      spacing: {
        unit: '4px',
        'margin-desktop': '24px',
        gutter: '16px',
        'margin-mobile': '12px',
        'card-padding': '16px',
      },
      fontFamily: {
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-md-mobile': ['Hanken Grotesk', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('tailwind-scrollbar')],
}
